# Generated by Django 5.2.14 on 2026-06-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_ingredient_reciperating"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(to="app.ingredient"),
        ),
    ]
